name: svpnn
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - colorama=0.4.5
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jedi=0.18.1
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.2
  - nest-asyncio=1.5.5
  - openssl=1.1.1q
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=22.1.2
  - prompt-toolkit=3.0.20
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.13
  - python-dateutil=2.8.2
  - pywin32=302
  - pyzmq=23.2.0
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.39.2
  - stack_data=0.2.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - zeromq=4.3.4
  - pip:
    - absl-py==1.1.0
    - appdirs==1.4.4
    - astroid==2.12.11
    - attrs==22.1.0
    - autopep8==1.7.0
    - cachetools==5.2.0
    - chardet==4.0.0
    - charset-normalizer==2.1.0
    - clean-fid==0.1.24
    - cycler==0.11.0
    - dill==0.3.5.1
    - fastjsonschema==2.16.1
    - fonttools==4.33.3
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - idna==2.10
    - imageio==2.21.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipywidgets==8.0.1
    - isort==5.10.1
    - joblib==1.1.0
    - jsonschema==4.14.0
    - jupyterlab-widgets==3.0.2
    - kiwisolver==1.4.3
    - lazy-object-proxy==1.7.1
    - mako==1.2.1
    - mapextrackt==0.4.8.6
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mccabe==0.7.0
    - nbformat==5.4.0
    - networkx==2.8.6
    - numpy==1.23.0
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.4.3
    - pillow==9.1.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - plotly==5.10.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pycuda==2022.1
    - pydotz==1.5.1
    - pylint==2.15.4
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-graphviz==0.20.1
    - pytools==2022.1.12
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - requests==2.25.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.8.1
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorwatch==0.9.1
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.5
    - torch==1.8.0+cu111
    - torchsummary==1.5.1
    - torchvision==0.9.0+cu111
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - widgetsnbextension==4.0.2
    - wrapt==1.14.1
    - zipp==3.8.0
